### ISSUE TITLE
[Question] Sending SMS to multiple destination address

### ISSUE THREAD

**Issue by elhananjair** [telecomsxchange/smpp-client-nodejs#18]
Hello there, I am trying to use this js script to try out sending SMS by connecting to SMPP Server, my question is it possible to send the same message to multiple phone numbers?

Thanks

**Comment by ajamous** [comment]
Yes, it is possible to send the same message to multiple phone numbers. You can achieve this by creating a loop to iterate through an array of phone numbers and call the function that sends the message. Here is an example for inspiration :

```javascript
let phoneNumbers = ['1234567890', '0987654321', '1122334455']; // your array of phone numbers
let message = 'Your SMS text here'; // your SMS message

for(let i = 0; i < phoneNumbers.length; i++) {
    sendSMS(phoneNumbers[i], message); // assuming sendSMS is your function to send a message
}
```

This will send the message to each phone number in the array. You just need to ensure that the `sendSMS` function is equipped to handle multiple simultaneous or sequential requests. If it isn't, you may need to modify it or add some delay between each send operation.

**Comment by elhananjair** [comment]
isn't `submit_multi` function better for sending to multiple destinations? Since it provides a way to send the same message to several different subscribers simultaneously.

My second question is it a good idea to use async in such a situation or blocking is the right way to go?

Thanks again.

**Comment by ajamous** [comment]
> isn't `submit_multi` function better for sending to multiple destinations? Since it provides a way to send the same message to several different subscribers simultaneously.
> 
> 
> 
> My second question is it a good idea to use async in such a situation or blocking is the right way to go?
> 

Could you provide further details about your specific use case? It would enable us to offer more tailored and relevant recommendations.

**Comment by elhananjair** [comment]
> Could you provide further details about your specific use case? It would enable us to offer more tailored and relevant recommendations.

Well, I am trying to set up an SMPP client that sends the same SMS content to different subscribers. The number of users will increase daily as they subscribe to the service, and I got an updated list daily from ISP (SMS-C) in CSV format, and in my application, I want to import that CSV file which contains the client's phone numbers, and send the same SMS to all each day. 

That's what I am trying to achieve with smpp-node library.

**Comment by ajamous** [comment]
> > Could you provide further details about your specific use case? It would enable us to offer more tailored and relevant recommendations.
> 
> 
> 
> Well, I am trying to set up an SMPP client that sends the same SMS content to different subscribers. The number of users will increase daily as they subscribe to the service, and I got an updated list daily from ISP (SMS-C) in CSV format, and in my application, I want to import that CSV file which contains the client's phone numbers, and send the same SMS to all each day. 
> 
> 
> 
> That's what I am trying to achieve with smpp-node library. 

It should be feasible to accomplish this using a loop, which shouldn't present any problems. My preference for this approach is largely due to potential rate limiting imposed by your SMS provider, coupled with the possible lack of support for submit_multi. I also find this method simpler for error handling.

Still, if your SMS provider does support submit_multi, feel free to try it out and modify the script to incorporate it. I trust you'll find this information useful.

**Comment by elhananjair** [comment]
Ok, thanks I will try it both ways. is using the async function better in this situation though?

**Comment by ajamous** [comment]
> Ok, thanks I will try it both ways. is using the async function better in this situation though? 

Yes. For your use case I think using async makes more sense.

**Comment by elhananjair** [comment]
Ok, thank you.

**Comment by elhananjair** [comment]
Hello @ajamous  I am sorry to bother you, but I don't where else I should go, there is no great forum regarding SMPP.

I was trying to connect to a real SMSC and I keep getting **command_status=14** here is my code:
```
var smpp = require('smpp');
var session = smpp.connect({
        url: 'smpp://HOST_NAME:PORT',
        auto_enquire_link_period: 10000,
        debug: true
}, function() {
        session.bind_transceiver({
                system_id: 'ID', //Some number
                password: 'password', //8 
                interface_version: '0x34',
                system_type: '0x00',
                addr_ton: '0x00',
                addr_npi: '0x00',
                address_range: '0x00'
        }, function(pdu) {
                if (pdu.command_status === 0) {
                        // Successfully bound
                       console.log("Successfully Created Bound");
                }else if(pdu.command_status === 14){  
                      console.log("Invalid Password");
                }
        });
});

session.on('deliver_sm', (pdu) => {
    const { short_message, destination_addr, esm_class} = pdu;
    if(esm_class !== 4 && short_message.message === 'ok') { //Indicates Message Type and enhanced network services, if it's 4 then it's a delivery receipt >
        console.log("Recieved SMS");
    }
    console.log("PDU IS : " + pdu);
})



session.on('error', (e) => {
    if(e.code === 'ETIMEOUT') {
        console.log("Connection to SMS-C Timeout");
    }else if(e.code === 'ECONNREFUSED'){
        console.log("Connection to SMS-C Refused")
    }else if(e.code === 'EAI_AGAIN'){
        console.log("Connection to internet is lost!");
    }else {
        console.log(`There is something wrong connecting to SMS-C, Error code: ${e.code}` );
    }
})
session.on('debug', function(type, msg, payload) {
        console.log({type: type, msg: msg, payload: payload});
});
```

I just read about command_status = 14 and it's about an invalid password but I really couldn't understand how that is possible. Can such restrictions be applied on the SMPP Server side? The password is right as far as I know.

**Comment by ajamous** [comment]
> Hello @ajamous I am sorry to bother you, but I don't where else I should go, there is no great forum regarding SMPP.
> 
> I was trying to connect to a real SMSC and I keep getting **command_status=14** here is my code:
> 
> ```
> var smpp = require('smpp');
> var session = smpp.connect({
>         url: 'smpp://HOST_NAME:PORT',
>         auto_enquire_link_period: 10000,
>         debug: true
> }, function() {
>         session.bind_transceiver({
>                 system_id: 'ID', //Some number
>                 password: 'password', //8 
>                 interface_version: '0x34',
>                 system_type: '0x00',
>                 addr_ton: '0x00',
>                 addr_npi: '0x00',
>                 address_range: '0x00'
>         }, function(pdu) {
>                 if (pdu.command_status === 0) {
>                         // Successfully bound
>                        console.log("Successfully Created Bound");
>                 }else if(pdu.command_status === 14){  
>                       console.log("Invalid Password");
>                 }
>         });
> });
> 
> session.on('deliver_sm', (pdu) => {
>     const { short_message, destination_addr, esm_class} = pdu;
>     if(esm_class !== 4 && short_message.message === 'ok') { //Indicates Message Type and enhanced network services, if it's 4 then it's a delivery receipt >
>         console.log("Recieved SMS");
>     }
>     console.log("PDU IS : " + pdu);
> })
> 
> 
> 
> session.on('error', (e) => {
>     if(e.code === 'ETIMEOUT') {
>         console.log("Connection to SMS-C Timeout");
>     }else if(e.code === 'ECONNREFUSED'){
>         console.log("Connection to SMS-C Refused")
>     }else if(e.code === 'EAI_AGAIN'){
>         console.log("Connection to internet is lost!");
>     }else {
>         console.log(`There is something wrong connecting to SMS-C, Error code: ${e.code}` );
>     }
> })
> session.on('debug', function(type, msg, payload) {
>         console.log({type: type, msg: msg, payload: payload});
> });
> ```
> 
> I just read about command_status = 14 and it's about an invalid password but I really couldn't understand how that is possible. Can such restrictions be applied on the SMPP Server side? The password is right as far as I know.

Sorry for the delay, I just noticed this message. 

Try to change this block of code to see the ${pdu.command_status} instead of just command_status 14 when the bind fails.
```js
 if (pdu.command_status === 0) {
            console.log("Successfully Created Bound");
        } else {
            console.log(`Error: ${pdu.command_status}`);
            console.log(pdu); // Log the whole PDU
```

**Comment by elhananjair** [comment]
Hello @ajamous thank you for replying, I just figured out that the password they gave me is incorrect, but the error code is very ambiguous since there is an error code for the incorrect password, An invalid password has a different meaning.

Currently, I am struggling with another issue, getting MO messages. I am listening for `deliver_sm` event, and with the `esm_class` parameter.  So if `esm_class` is different from 4 it is MO message as far as I know. The tricky part is I do receive MO messages but the SMSC has two keywords assigned to our server and those are 'Ok' to subscribe to our daily sent SMS and 'Stop' to unsubscribe. The problem I do receive every MO message sent by clients except for 'Ok' and 'Stop'. I don't know if there is another way of listening to that specific keywords in SMPP.

```
session.on('deliver_sm', (pdu) => {
    if(pdu.esm_class === 4){ //esm_class Indicates Message Mode and Message Type,
        let stat = pdu.short_message.message.substring(pdu.short_message.message.search('stat')+5, pdu.short_message.message.search('stat')+12);
        if(stat === 'DELIVRD'){
            console.log("Delivery report: " + pdu.source_addr);
            session.send(pdu.response()); 
        }else {
            console.log("Undelivered " + stat + pdu.source_addr)
        }
    }else if(pdu.esm_class !== 4){
        console.log(pdu.short_message);
    }
})
```
