### ISSUE TITLE
How to test message

### ISSUE THREAD

**Issue by bc070200824** [telecomsxchange/smpp-client-nodejs#2]
Hi, I'm new in telecom xchange, this is not issue, actually I want help to understand how to send test message using smpp client node.js. So please let me know, if I want to send a test message, what things are needed to change in send.js file, I can use the command "node send.js", but I need to change credentials inside send.js file, which is unable to comprehend for me..

I need following clarification.
1. var session = smpp.connect('smpp://smpp01.telecomsxchange.com:2776');
Can replace it as if I have a static IP (where SMPP server resides)
  var session = smpp.connect('smpp://192.168.8.101:2776');

2. system_id: '{SMPP System_UD}',
    while giving SMPP system id curly brackets are to place along with or not? 
   Can I do as
  system_id: 'abc',
3. destination_addr: '19542400000',
   what is thing? is it the recipient cell number or some thing else? if it is not recipient number then where to insert recipient cell number..

**Comment by telecomsxchange** [comment]
Hello @bc070200824 

> Hi, I'm new in telecom xchange, this is not issue, actually I want help to understand how to send test message using smpp client node.js. So please let me know, if I want to send a test message, what things are needed to change in send.js file, I can use the command "node send.js", but I need to change credentials inside send.js file, which is unable to comprehend for me..
> 
> I need following clarification.
> 
> 1. var session = smpp.connect('smpp://smpp01.telecomsxchange.com:2776');
>    Can replace it as if I have a static IP (where SMPP server resides
>    var session = smpp.connect('smpp://192.168.8.101:2776');

You need to keep the destination SMPP host as TelecomsXChange domain/ip, see below: 

```javascript
var session = smpp.connect('smpp://smpp01.telecomsxchange.com:2776'); as this is the 
```
You can whitelist your static IP address in TelecomsXChange Buyer portal under accounts page.


> 2. system_id: '{SMPP System_UD}',
>    while giving SMPP system id curly brackets are to place along with or not?
>    Can I do as
>    system_id: 'abc',

Yes system_id: 'abc' is the correct format. You can generate system_id and password from buyers portal. 

> 3. destination_addr: '19542400000',
>    what is thing? is it the recipient cell number or some thing else? if it is not recipient number then where to insert recipient cell number..

This is the destination phone number you want to send the message to. replace this with the real phone number you want to send the message to.

Please test and let us know if you face any issues.
